# Generated by Django 4.0.3 on 2022-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='Puncture', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_part', models.CharField(default='mcarFix', max_length=100)),
                ('price_of_part', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_make', models.CharField(choices=[('toyota', 'toyota'), ('vits', 'vits'), ('tsunami', 'tsunami'), ('isuzu', 'isuzu'), ('Nissan', 'Nissan')], default='toyota', max_length=50)),
                ('car_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_mechanic', models.CharField(max_length=100)),
                ('service', models.ManyToManyField(to='carinvfile.servicestable')),
            ],
        ),
    ]
